/* =============================================================
   PROJETO 66 — Banco de conteúdo motivacional
   Regras de direitos autorais respeitadas:
   - Versículos: tradução João Ferreira de Almeida (domínio público)
   - Autores: apenas citações curtas amplamente conhecidas, com crédito
   - Demais frases: originais ou paráfrases marcadas como "inspirado em"
   Categorias: versiculo, disciplina, lideranca, masculinidade,
               responsabilidade, familia, crescimento, fe, foco
   ============================================================= */
'use strict';

P66.QUOTES = [
  /* ---------- Versículos (Almeida, domínio público) ---------- */
  { t: 'Tudo posso naquele que me fortalece.', a: 'Filipenses 4:13', c: 'versiculo' },
  { t: 'O Senhor é o meu pastor; nada me faltará.', a: 'Salmos 23:1', c: 'versiculo' },
  { t: 'Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma cidade.', a: 'Provérbios 16:32', c: 'versiculo' },
  { t: 'Vai ter com a formiga, ó preguiçoso; olha para os seus caminhos e sê sábio.', a: 'Provérbios 6:6', c: 'versiculo' },
  { t: 'Esforçai-vos, e ele fortalecerá o vosso coração, vós todos que esperais no Senhor.', a: 'Salmos 31:24', c: 'versiculo' },
  { t: 'Não to mandei eu? Esforça-te e tem bom ânimo; não pasmes, nem te espantes.', a: 'Josué 1:9', c: 'versiculo' },
  { t: 'Buscai primeiro o reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas.', a: 'Mateus 6:33', c: 'versiculo' },
  { t: 'A resposta branda desvia o furor.', a: 'Provérbios 15:1', c: 'versiculo' },
  { t: 'Combati o bom combate, acabei a carreira, guardei a fé.', a: '2 Timóteo 4:7', c: 'versiculo' },
  { t: 'Corramos com paciência a carreira que nos está proposta.', a: 'Hebreus 12:1', c: 'versiculo' },
  { t: 'Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', a: '2 Timóteo 1:7', c: 'versiculo' },
  { t: 'O que segue a justiça e a beneficência achará a vida, a justiça e a honra.', a: 'Provérbios 21:21', c: 'versiculo' },
  { t: 'Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo.', a: 'Provérbios 27:17', c: 'versiculo' },
  { t: 'Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.', a: 'Provérbios 3:5', c: 'versiculo' },
  { t: 'Os que esperam no Senhor renovarão as suas forças, subirão com asas como águias.', a: 'Isaías 40:31', c: 'versiculo' },
  { t: 'Vigiai e orai, para que não entreis em tentação.', a: 'Mateus 26:41', c: 'versiculo' },
  { t: 'Ensina-nos a contar os nossos dias, de tal maneira que alcancemos corações sábios.', a: 'Salmos 90:12', c: 'versiculo' },
  { t: 'Tudo quanto te vier à mão para fazer, faze-o conforme as tuas forças.', a: 'Eclesiastes 9:10', c: 'versiculo' },
  { t: 'O preguiçoso deseja, e coisa nenhuma alcança, mas a alma dos diligentes se farta.', a: 'Provérbios 13:4', c: 'versiculo' },
  { t: 'Eu e a minha casa serviremos ao Senhor.', a: 'Josué 24:15', c: 'versiculo' },
  { t: 'Sê fiel até a morte, e dar-te-ei a coroa da vida.', a: 'Apocalipse 2:10', c: 'versiculo' },
  { t: 'Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.', a: 'Salmos 119:105', c: 'versiculo' },
  { t: 'Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja.', a: 'Efésios 5:25', c: 'versiculo' },
  { t: 'Quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus.', a: '1 Coríntios 10:31', c: 'versiculo' },
  { t: 'As suas misericórdias não têm fim; novas são cada manhã.', a: 'Lamentações 3:22-23', c: 'versiculo' },
  { t: 'Não sabeis vós que o vosso corpo é o templo do Espírito Santo?', a: '1 Coríntios 6:19', c: 'versiculo' },
  { t: 'Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as saídas da vida.', a: 'Provérbios 4:23', c: 'versiculo' },
  { t: 'Se Deus é por nós, quem será contra nós?', a: 'Romanos 8:31', c: 'versiculo' },
  { t: 'Aquietai-vos, e sabei que eu sou Deus.', a: 'Salmos 46:10', c: 'versiculo' },
  { t: 'Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele.', a: 'Provérbios 22:6', c: 'versiculo' },
  { t: 'Andai como filhos da luz.', a: 'Efésios 5:8', c: 'versiculo' },
  { t: 'Remindo o tempo, porquanto os dias são maus.', a: 'Efésios 5:16', c: 'versiculo' },
  { t: 'Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto.', a: 'Salmos 51:10', c: 'versiculo' },
  { t: 'O choro pode durar uma noite, mas a alegria vem pela manhã.', a: 'Salmos 30:5', c: 'versiculo' },

  /* ---------- Disciplina ---------- */
  { t: 'Disciplina é igual a liberdade.', a: 'Jocko Willink', c: 'disciplina' },
  { t: 'Ninguém está vindo te salvar. Levanta e executa.', a: 'Inspirado em David Goggins', c: 'disciplina' },
  { t: 'Quando achar que acabou, você usou só 40% do que tem.', a: 'Inspirado em David Goggins', c: 'disciplina' },
  { t: 'A cama vence quem não tem missão.', a: null, c: 'disciplina' },
  { t: 'Motivação é volátil. Disciplina é infraestrutura.', a: null, c: 'disciplina' },
  { t: 'O treino que você não quer fazer é o que mais importa.', a: null, c: 'disciplina' },
  { t: 'Faça o difícil enquanto está fácil recusar.', a: null, c: 'disciplina' },
  { t: 'Sua rotina de hoje é a sua biografia em rascunho.', a: null, c: 'disciplina' },
  { t: 'Você não decide seu futuro. Decide seus hábitos — e eles decidem seu futuro.', a: null, c: 'disciplina' },
  { t: 'O despertador é o primeiro inimigo do dia. Vença-o.', a: null, c: 'disciplina' },
  { t: 'A repetição entediante é o preço da excelência.', a: null, c: 'disciplina' },
  { t: 'Nenhum hábito é pequeno quando repetido 66 vezes.', a: null, c: 'disciplina' },
  { t: 'Conforto agora, arrependimento depois. Escolha uma vez só.', a: null, c: 'disciplina' },
  { t: 'Disciplina é lembrar do que você quer de verdade.', a: null, c: 'disciplina' },
  { t: 'Quem domina a manhã não é dominado pelo dia.', a: null, c: 'disciplina' },
  { t: 'Você não precisa de vontade. Precisa de um horário.', a: null, c: 'disciplina' },
  { t: 'Constância silenciosa vale mais que intensidade barulhenta.', a: null, c: 'disciplina' },
  { t: 'Cansaço passa. Desistência fica.', a: null, c: 'disciplina' },
  { t: 'Ordem externa começa com ordem interna — e vice-versa.', a: null, c: 'disciplina' },
  { t: 'A preguiça cobra juros. A disciplina paga dividendos.', a: null, c: 'disciplina' },
  { t: 'O corpo obedece a quem manda todos os dias.', a: null, c: 'disciplina' },
  { t: 'Não negocie com o travesseiro. Ele sempre vence a negociação.', a: null, c: 'disciplina' },
  { t: 'Um dia quebrado não quebra o homem. Dois começam a quebrar.', a: null, c: 'disciplina' },
  { t: 'Trate seus hábitos como compromissos com alguém que você respeita: você.', a: null, c: 'disciplina' },
  { t: 'Faça a cama. Vença a primeira batalha antes das 6h.', a: 'Inspirado em William McRaven', c: 'disciplina' },
  { t: 'Hoje difícil, amanhã forte. Hoje fácil, amanhã fraco.', a: null, c: 'disciplina' },
  { t: 'A rotina certa transforma esforço em identidade.', a: null, c: 'disciplina' },
  { t: 'Quem falha em treinar, treina a falhar.', a: null, c: 'disciplina' },
  { t: 'Cinco minutos de ação matam uma hora de ansiedade.', a: null, c: 'disciplina' },
  { t: 'Seja o homem que aparece. Todos os dias. Sem plateia.', a: null, c: 'disciplina' },

  /* ---------- Liderança ---------- */
  { t: 'Um líder conhece o caminho, segue o caminho e mostra o caminho.', a: 'John C. Maxwell', c: 'lideranca' },
  { t: 'Liderança é influência — nada mais, nada menos.', a: 'John C. Maxwell', c: 'lideranca' },
  { t: 'Assuma o comando do seu dia ou alguém assumirá por você.', a: null, c: 'lideranca' },
  { t: 'Responsabilidade extrema: não há mau pelotão, há mau comandante.', a: 'Inspirado em Jocko Willink', c: 'lideranca' },
  { t: 'Liderar é servir primeiro e ser servido nunca.', a: null, c: 'lideranca' },
  { t: 'Sua família segue o seu exemplo, não o seu discurso.', a: null, c: 'lideranca' },
  { t: 'O líder que não se governa não governa ninguém.', a: null, c: 'lideranca' },
  { t: 'Calma é contagiosa. Pânico também. Escolha o que espalhar.', a: null, c: 'lideranca' },
  { t: 'Comece com o fim em mente.', a: 'Stephen Covey', c: 'lideranca' },
  { t: 'Primeiro o mais importante.', a: 'Stephen Covey', c: 'lideranca' },
  { t: 'Entre o estímulo e a resposta há um espaço. Nele mora sua liberdade.', a: 'Inspirado em Viktor Frankl', c: 'lideranca' },
  { t: 'Grandes líderes fazem reuniões consigo mesmos todas as manhãs.', a: null, c: 'lideranca' },
  { t: 'Quem lidera a própria agenda lidera a própria vida.', a: null, c: 'lideranca' },
  { t: 'Autoridade se recebe. Respeito se constrói diariamente.', a: null, c: 'lideranca' },
  { t: 'O padrão que você tolera é o padrão que você lidera.', a: null, c: 'lideranca' },
  { t: 'Decida cedo, corrija rápido, aprenda sempre.', a: null, c: 'lideranca' },
  { t: 'Um homem no comando de si mesmo é raro — e insubstituível.', a: null, c: 'lideranca' },
  { t: 'Delegue tarefas, nunca o caráter.', a: null, c: 'lideranca' },
  { t: 'Planeje na véspera. A batalha se vence antes dela começar.', a: null, c: 'lideranca' },
  { t: 'Líderes leem. Quem não lê, repete.', a: null, c: 'lideranca' },
  { t: 'Seja tão confiável que sua palavra dispense contrato.', a: null, c: 'lideranca' },
  { t: 'A disciplina do líder é a segurança dos liderados.', a: null, c: 'lideranca' },
  { t: 'Não reclame do time se você não treinou o time.', a: null, c: 'lideranca' },
  { t: 'Visão sem execução é alucinação.', a: null, c: 'lideranca' },

  /* ---------- Masculinidade ---------- */
  { t: 'Arrume o seu quarto antes de criticar o mundo.', a: 'Inspirado em Jordan Peterson', c: 'masculinidade' },
  { t: 'Fique de pé, com os ombros para trás.', a: 'Inspirado em Jordan Peterson', c: 'masculinidade' },
  { t: 'Compare-se com quem você era ontem, não com outra pessoa hoje.', a: 'Inspirado em Jordan Peterson', c: 'masculinidade' },
  { t: 'Um homem forte é perigoso sob controle — inofensivo é outra coisa.', a: 'Inspirado em Jordan Peterson', c: 'masculinidade' },
  { t: 'Força sem domínio próprio é apenas risco.', a: null, c: 'masculinidade' },
  { t: 'Homem que foge do desconforto foge de si mesmo.', a: null, c: 'masculinidade' },
  { t: 'Proteja, proveja, presida — em amor.', a: null, c: 'masculinidade' },
  { t: 'Seja a rocha da casa, não a tempestade.', a: null, c: 'masculinidade' },
  { t: 'Palavra dada é dívida de honra.', a: null, c: 'masculinidade' },
  { t: 'O homem maduro faz o necessário mesmo sem vontade.', a: null, c: 'masculinidade' },
  { t: 'Carregue peso. Físico e moral. É para isso que existem ombros.', a: null, c: 'masculinidade' },
  { t: 'Voluntarie-se para o difícil antes que o difícil te convoque.', a: null, c: 'masculinidade' },
  { t: 'Homens fortes criam tempos bons. Seja a exceção nos tempos fáceis.', a: null, c: 'masculinidade' },
  { t: 'Domar a língua é o primeiro campeonato do homem.', a: null, c: 'masculinidade' },
  { t: 'Sua esposa não precisa de um menino grande. Precisa de um homem constante.', a: null, c: 'masculinidade' },
  { t: 'Frieza na crise, calor no lar.', a: null, c: 'masculinidade' },
  { t: 'O espelho não mente: você é o resultado das suas repetições.', a: null, c: 'masculinidade' },
  { t: 'Menos desabafo, mais plano de ação.', a: null, c: 'masculinidade' },
  { t: 'Um homem sem rotina é um navio sem leme.', a: null, c: 'masculinidade' },
  { t: 'Coragem não é ausência de medo — é ação apesar dele.', a: null, c: 'masculinidade' },
  { t: 'Aguente o desconforto em silêncio, celebre a vitória com gratidão.', a: null, c: 'masculinidade' },
  { t: 'Seu filho está te assistindo. Aja como se isso importasse — porque importa.', a: null, c: 'masculinidade' },
  { t: 'Homem de verdade pede perdão primeiro.', a: null, c: 'masculinidade' },
  { t: 'A força do homem se mede pelo que ele constrói, não pelo que destrói.', a: null, c: 'masculinidade' },

  /* ---------- Responsabilidade ---------- */
  { t: 'Se é para ser, depende de mim — debaixo de Deus.', a: null, c: 'responsabilidade' },
  { t: 'A culpa é sua. A solução também. Isso é ótimo.', a: null, c: 'responsabilidade' },
  { t: 'Dono dos resultados, não vítima das circunstâncias.', a: null, c: 'responsabilidade' },
  { t: 'Quem dá desculpa entrega o comando.', a: null, c: 'responsabilidade' },
  { t: 'Assuma o erro em 10 segundos e ganhe o dia de volta.', a: null, c: 'responsabilidade' },
  { t: 'Você é o CEO da sua vida. Aja como tal no primeiro turno.', a: null, c: 'responsabilidade' },
  { t: 'Prestação de contas não é peso — é proteção.', a: null, c: 'responsabilidade' },
  { t: 'O que não é medido escorrega. O que é medido melhora.', a: null, c: 'responsabilidade' },
  { t: 'Prometa menos. Cumpra mais. Sempre.', a: null, c: 'responsabilidade' },
  { t: 'Ninguém terceiriza flexão. Nem caráter.', a: null, c: 'responsabilidade' },
  { t: 'Sua palavra vale o que sua agenda mostra.', a: null, c: 'responsabilidade' },
  { t: 'Falhou? Registre, corrija, siga. Sem novela.', a: null, c: 'responsabilidade' },
  { t: 'Adulto é quem paga o preço antes de usar o produto.', a: null, c: 'responsabilidade' },
  { t: 'Responsabilidade é a assinatura do homem maduro.', a: null, c: 'responsabilidade' },
  { t: 'Não herde culpas, herde deveres.', a: null, c: 'responsabilidade' },
  { t: 'A liberdade cresce na exata medida da responsabilidade assumida.', a: null, c: 'responsabilidade' },
  { t: 'Cada hábito quebrado tem um motivo. Anote-o e elimine-o.', a: null, c: 'responsabilidade' },
  { t: 'Segunda-feira não é desculpa. É oportunidade com nome feio.', a: null, c: 'responsabilidade' },
  { t: 'O extrato bancário e a balança não aceitam narrativa.', a: null, c: 'responsabilidade' },
  { t: 'Vigie suas entradas: o que consome te consome.', a: null, c: 'responsabilidade' },
  { t: 'Quem se mede não se engana.', a: null, c: 'responsabilidade' },
  { t: 'A agenda revela a teologia prática de um homem.', a: null, c: 'responsabilidade' },
  { t: 'Autocomando hoje, autoridade amanhã.', a: null, c: 'responsabilidade' },
  { t: 'Erro confessado é aula. Erro escondido é dívida.', a: null, c: 'responsabilidade' },

  /* ---------- Família ---------- */
  { t: 'Nenhum sucesso compensa o fracasso no lar.', a: 'David O. McKay', c: 'familia' },
  { t: 'Sua esposa é aliança, não plateia.', a: null, c: 'familia' },
  { t: 'Filhos soletram amor assim: T-E-M-P-O.', a: null, c: 'familia' },
  { t: 'Ligue para seus pais. Um dia o telefone não vai tocar.', a: null, c: 'familia' },
  { t: 'O lar é o primeiro púlpito do homem.', a: null, c: 'familia' },
  { t: 'Celular na mesa, família em espera. Inverta.', a: null, c: 'familia' },
  { t: 'Ame sua esposa em público e em particular — na mesma medida.', a: null, c: 'familia' },
  { t: 'A herança que fica é o exemplo que você deu.', a: null, c: 'familia' },
  { t: 'Casa em ordem, coração em paz.', a: null, c: 'familia' },
  { t: 'Elogie sua esposa hoje. Amanhã de novo.', a: null, c: 'familia' },
  { t: 'Ore com sua família, não apenas pela sua família.', a: null, c: 'familia' },
  { t: 'O melhor presente para seus filhos é amar a mãe deles.', a: null, c: 'familia' },
  { t: 'Jantar sem tela é culto de comunhão.', a: null, c: 'familia' },
  { t: 'Perdoe rápido. A casa é pequena demais para orgulho grande.', a: null, c: 'familia' },
  { t: 'Trabalhe duro fora para estar inteiro dentro.', a: null, c: 'familia' },
  { t: 'A porta de casa deve ser a fronteira do estresse.', a: null, c: 'familia' },
  { t: 'Escute sua esposa sem consertar nada. Só escute.', a: null, c: 'familia' },
  { t: 'Data marcada com a família é reunião inadiável.', a: null, c: 'familia' },
  { t: 'Seu casamento é o seu ministério mais visível.', a: null, c: 'familia' },
  { t: 'Filho não precisa de herói perfeito, precisa de pai presente.', a: null, c: 'familia' },
  { t: 'Abrace mais. Estatísticas não abraçam ninguém.', a: null, c: 'familia' },
  { t: 'Construa memórias como quem constrói patrimônio.', a: null, c: 'familia' },

  /* ---------- Crescimento (Kaizen / Atomic Habits) ---------- */
  { t: 'Você não sobe até o nível das suas metas; você cai até o nível dos seus sistemas.', a: 'James Clear', c: 'crescimento' },
  { t: 'Melhorar 1% ao dia é ficar 37x melhor em um ano.', a: 'Inspirado em James Clear', c: 'crescimento' },
  { t: 'Cada ação é um voto na pessoa que você quer se tornar.', a: 'Inspirado em James Clear', c: 'crescimento' },
  { t: 'Não quebre a corrente duas vezes seguidas.', a: 'Inspirado em James Clear', c: 'crescimento' },
  { t: 'Torne o hábito óbvio, atraente, fácil e satisfatório.', a: 'Inspirado em James Clear', c: 'crescimento' },
  { t: 'Kaizen: hoje um pouco melhor que ontem. Sem exceção.', a: null, c: 'crescimento' },
  { t: 'Pequenos reparos evitam grandes reformas.', a: null, c: 'crescimento' },
  { t: 'O composto mais poderoso do mundo é o juro sobre hábito.', a: null, c: 'crescimento' },
  { t: 'Plante leitura, colha visão.', a: null, c: 'crescimento' },
  { t: 'Aprenda uma habilidade nova: é o seguro de vida da sua carreira.', a: null, c: 'crescimento' },
  { t: 'Meça a semana, não o humor do dia.', a: null, c: 'crescimento' },
  { t: 'Repetição é a mãe da maestria.', a: null, c: 'crescimento' },
  { t: 'Devagar é suave. Suave é rápido.', a: 'Lema militar', c: 'crescimento' },
  { t: 'Um livro por mês te coloca em outra classe em cinco anos.', a: null, c: 'crescimento' },
  { t: 'Falhar faz parte do treino. Desistir não.', a: null, c: 'crescimento' },
  { t: 'Aprendiz todos os dias, mestre em alguns anos.', a: null, c: 'crescimento' },
  { t: 'Progresso visível alimenta progresso contínuo.', a: null, c: 'crescimento' },
  { t: 'Revise a semana como um técnico revê o jogo.', a: null, c: 'crescimento' },
  { t: 'A planilha de hoje é o troféu de dezembro.', a: null, c: 'crescimento' },
  { t: 'Identidade primeiro: seja um leitor, e a leitura acontece.', a: null, c: 'crescimento' },
  { t: 'Erros documentados viram sabedoria. Erros ignorados viram rotina.', a: null, c: 'crescimento' },
  { t: 'O dia 66 se constrói no dia 1, 2, 3...', a: null, c: 'crescimento' },
  { t: 'Ambiente vence força de vontade: prepare o terreno.', a: null, c: 'crescimento' },
  { t: 'Não conte os dias. Faça os dias contarem.', a: 'Muhammad Ali', c: 'crescimento' },
  { t: 'A melhor hora de plantar uma árvore foi há 20 anos. A segunda melhor é agora.', a: 'Provérbio chinês', c: 'crescimento' },
  { t: 'Excelência é hábito, não ato.', a: 'Inspirado em Aristóteles', c: 'crescimento' },

  /* ---------- Fé ---------- */
  { t: 'Ore como se tudo dependesse de Deus. Trabalhe como se tudo dependesse de você.', a: 'Atribuído a Agostinho', c: 'fe' },
  { t: 'A oração da manhã afina o instrumento do dia.', a: null, c: 'fe' },
  { t: 'Joelhos no chão pela manhã, coluna ereta o dia inteiro.', a: null, c: 'fe' },
  { t: 'Quem abre o dia com a Palavra fecha o dia com paz.', a: null, c: 'fe' },
  { t: 'Fé sem obras é teoria. Obras sem fé é vaidade.', a: null, c: 'fe' },
  { t: 'Devocional não é obrigação — é abastecimento.', a: null, c: 'fe' },
  { t: 'A Bíblia lida transforma; a Bíblia na estante decora.', a: null, c: 'fe' },
  { t: 'Deus honra o homem que honra os compromissos invisíveis.', a: null, c: 'fe' },
  { t: 'Trabalhe com excelência: seu ofício também é altar.', a: null, c: 'fe' },
  { t: 'Gratidão de manhã é blindagem contra a murmuração à tarde.', a: null, c: 'fe' },
  { t: 'Santidade nos detalhes: como você faz uma coisa é como faz tudo.', a: null, c: 'fe' },
  { t: 'O silêncio diante de Deus organiza o barulho de dentro.', a: null, c: 'fe' },
  { t: 'Caráter é quem você é quando só Deus está vendo.', a: null, c: 'fe' },
  { t: 'Semeie fidelidade no oculto; a colheita vem em público.', a: null, c: 'fe' },
  { t: 'Cristo no centro, o resto em ordem.', a: null, c: 'fe' },
  { t: 'A alma também tem agenda: reserve o primeiro horário.', a: null, c: 'fe' },
  { t: 'Adore antes de rolar o feed.', a: null, c: 'fe' },
  { t: 'Um homem de joelhos vê mais longe que um homem no pedestal.', a: null, c: 'fe' },
  { t: 'Descanso também é mandamento. Durma como quem confia.', a: null, c: 'fe' },
  { t: 'Provações são academias da fé.', a: null, c: 'fe' },
  { t: 'Evangelizar é transbordar, não performar.', a: null, c: 'fe' },
  { t: 'Deus não procura homens perfeitos — procura homens disponíveis.', a: null, c: 'fe' },

  /* ---------- Foco ---------- */
  { t: 'Foco é dizer não para mil coisas boas.', a: 'Inspirado em Steve Jobs', c: 'foco' },
  { t: 'Uma missão por vez. Conclua. Próxima.', a: null, c: 'foco' },
  { t: 'O celular no bolso é uma reunião que nunca acaba. Encerre-a.', a: null, c: 'foco' },
  { t: 'Multitarefa é fazer duas coisas mal ao mesmo tempo.', a: null, c: 'foco' },
  { t: 'Profundidade gera valor. Distração gera desculpas.', a: null, c: 'foco' },
  { t: 'Notificação não é urgência. É interrupção com fantasia.', a: null, c: 'foco' },
  { t: 'Proteja suas manhãs como um cofre.', a: null, c: 'foco' },
  { t: '25 minutos de foco total valem 3 horas de atenção picada.', a: null, c: 'foco' },
  { t: 'O modo avião também serve para decolar projetos.', a: null, c: 'foco' },
  { t: 'Comece pela rã: a tarefa mais difícil, primeiro.', a: 'Inspirado em Brian Tracy', c: 'foco' },
  { t: 'Onde vai sua atenção, vai sua vida.', a: null, c: 'foco' },
  { t: 'Menos abas abertas, mais capítulos fechados.', a: null, c: 'foco' },
  { t: 'Diga não hoje para poder dizer sim ao que importa.', a: null, c: 'foco' },
  { t: 'Ocupado é diferente de produtivo. Meça resultado, não movimento.', a: null, c: 'foco' },
  { t: 'A tela que você evita à noite devolve o foco pela manhã.', a: null, c: 'foco' },
  { t: 'Grandes obras nascem de blocos de silêncio.', a: null, c: 'foco' },
  { t: 'Se tudo é prioridade, nada é prioridade.', a: null, c: 'foco' },
  { t: 'Cronômetro rodando, mundo esperando.', a: null, c: 'foco' },
  { t: 'Termine o que começou. É raro. Seja raro.', a: null, c: 'foco' },
  { t: 'Um homem focado é uma força da natureza.', a: null, c: 'foco' },
];

/* Sorteio anti-repetição: evita as últimas N frases exibidas */
P66.pickQuote = function (recentIdx) {
  const total = P66.QUOTES.length;
  const recent = new Set(recentIdx || []);
  let idx, guard = 0;
  do {
    idx = Math.floor(Math.random() * total);
    guard++;
  } while (recent.has(idx) && guard < 200);
  return idx;
};
